# Generated by Django 3.1.7 on 2022-03-15 03:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Cosec')),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Cosec',
                'verbose_name_plural': 'Cosec',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Franja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Franja')),
                ('hora_inicial', models.IntegerField(verbose_name='Hora Inicial')),
                ('hora_final', models.IntegerField(verbose_name='Hora Final')),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Franja de Intervenciòn',
                'verbose_name_plural': 'Franja de Intervenciòn',
                'ordering': ['hora_inicial'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Localidad')),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Punto')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Punto',
                'verbose_name_plural': 'Puntos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo Usuario')),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipo de Usuario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(default='', max_length=100, verbose_name='Usuario')),
                ('fechadelturno', models.DateField(default='')),
                ('asistio', models.BooleanField(default=False)),
                ('ingreso_a_las', models.DateTimeField(default='', null=True)),
                ('salio_a_las', models.DateTimeField(default='', null=True)),
                ('cosec', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sigetmeapp.cosec')),
                ('franja', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sigetmeapp.franja')),
                ('localidad', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sigetmeapp.localidad')),
                ('punto', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sigetmeapp.punto')),
                ('usuarioturno', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turnos',
                'verbose_name_plural': 'Turnos',
                'ordering': ['cosec', 'franja'],
            },
        ),
    ]
