# Generated by Django 3.1.7 on 2022-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigetmeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='creado_por',
            field=models.CharField(default='', max_length=100, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='ingreso_a_las',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='salio_a_las',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
