# Generated by Django 3.1.7 on 2022-07-23 02:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType2',
            fields=[
                ('BoxType', models.IntegerField(primary_key=True, serialize=False, verbose_name='Type of Box')),
                ('QtySmallBox', models.IntegerField(default=0, verbose_name='Qty in SmallBox')),
                ('SizeSmallBox', models.CharField(default='8x6x4', max_length=30, verbose_name='Size Small Box')),
                ('QtySmallBox_inMaster', models.IntegerField(default=0, verbose_name='Qty of SmallBox in Master Box')),
                ('SizeMasterBox', models.CharField(default='12x12x12', max_length=30, verbose_name='Size Master Box')),
                ('WeighMasterBox', models.IntegerField(default=0, verbose_name='Gross Weight')),
                ('NetWeighMasterBox', models.IntegerField(default=0, verbose_name='Net Weight')),
            ],
            options={
                'verbose_name': 'Box Type',
                'verbose_name_plural': 'Box Type',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipTo', models.CharField(default='', max_length=100, verbose_name='ShipTo')),
                ('zipcode', models.CharField(default='', max_length=10, verbose_name='ZipCode')),
                ('citi', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.cities')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.customer')),
            ],
            options={
                'verbose_name': 'Ship To',
                'verbose_name_plural': 'Ship To',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Estate',
                'verbose_name_plural': 'Estates',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Po_number', models.CharField(default='', max_length=30, verbose_name='P.O Number')),
                ('So_number', models.CharField(default='', max_length=30, verbose_name='S.O Number')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('Special_Inst', models.TextField(default='', max_length=300, verbose_name='Special Inst.')),
                ('Procesed', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=30, verbose_name='Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('barcode', models.CharField(default='123456789', max_length=30, verbose_name='Barcode')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Rep Name')),
            ],
            options={
                'verbose_name': 'Representant',
                'verbose_name_plural': 'Representant',
            },
        ),
        migrations.CreateModel(
            name='WeightSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoxNumber', models.IntegerField(default=0, verbose_name='Qty Label for Small Box')),
                ('ProductName', models.CharField(default='12x12x12', max_length=100, verbose_name='Size Master Box')),
                ('Weight', models.IntegerField(default=0, verbose_name='Qty Label for Small Box')),
                ('Dimensions', models.CharField(default='12x12x12', max_length=30, verbose_name='Size Master Box')),
                ('Orderx', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.order')),
            ],
            options={
                'verbose_name': 'WeightSheet',
                'verbose_name_plural': 'WeightSheet',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered_Qty', models.IntegerField(default=0, verbose_name='Ordered Qty ')),
                ('QtySmallBox', models.IntegerField(default=0, null=True, verbose_name='Qty of Small Boxes')),
                ('QtyBigBox', models.IntegerField(default=0, null=True, verbose_name='Qty of Master Boxes')),
                ('Orden', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.order')),
                ('Prod', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.product', verbose_name='Product ')),
            ],
            options={
                'verbose_name': 'Order Details',
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='rep',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.reps'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.destinos'),
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgLabelSmallBox', models.CharField(default='.png', max_length=30, verbose_name='IImage barcode for Master Box')),
                ('ImgLabelMasterBox', models.CharField(default='.png', max_length=30, verbose_name='Image barcode for Master Box ')),
                ('LabelAuxliar', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='S', max_length=1)),
                ('SKU', models.CharField(default='12x12x12', max_length=30, verbose_name='SKU')),
                ('EtiquetaMasterBox', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='S', max_length=1)),
                ('QtyEtiquetes', models.IntegerField(default=4, verbose_name='Qty de Etiquetas')),
                ('BoxType', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.boxtype2')),
                ('Customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.customer')),
                ('Prod', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.product')),
            ],
            options={
                'verbose_name': 'Matrix',
                'verbose_name_plural': 'Matrix',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.estados'),
        ),
        migrations.AddField(
            model_name='boxtype2',
            name='cust_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.customer'),
        ),
    ]
