# Generated by Django 3.1.7 on 2022-07-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailsInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(default='', max_length=100, verbose_name='Size Master Box')),
                ('Cantidad', models.IntegerField(default=0, verbose_name='Ordered Qty ')),
                ('Orden', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.order')),
            ],
            options={
                'verbose_name': 'Order Details Label',
                'verbose_name_plural': 'Order Details Label',
            },
        ),
    ]
