# Generated by Django 3.1.7 on 2022-09-20 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0002_orderdetailsinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100, verbose_name='Contractor Name')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email Contractor')),
                ('Phone', models.CharField(default='', max_length=100, verbose_name='Phone Contractor')),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100, verbose_name='Contractor Name')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterField(
            model_name='matrix',
            name='ImgLabelSmallBox',
            field=models.CharField(default='.png', max_length=30, verbose_name='Image barcode for Small Box'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='SKU',
            field=models.CharField(default='', max_length=30, verbose_name='SKU'),
        ),
        migrations.CreateModel(
            name='OrderContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('Contractor', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.contractor')),
                ('Project', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.project')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
