# Generated by Django 3.1.7 on 2022-09-20 02:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0003_auto_20220919_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercontractor',
            options={'verbose_name': 'Order Contractor', 'verbose_name_plural': 'Orders Contractor'},
        ),
        migrations.CreateModel(
            name='OrderContractorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty_Req', models.IntegerField(default=0, verbose_name='Qty Required')),
                ('Qty_Delivery', models.IntegerField(default=0, verbose_name='Qty Deliveried')),
                ('Sellado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('Barcode', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('Other', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Delivery Date')),
                ('Orden', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.ordercontractor')),
                ('Product', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.product')),
            ],
            options={
                'verbose_name': 'OrderContractorDetail',
                'verbose_name_plural': 'OrderContractorDetail',
            },
        ),
    ]
