# Generated by Django 3.1.7 on 2022-09-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0004_auto_20220919_2212'),
    ]


