# Generated by Django 3.1.7 on 2022-09-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0005_auto_20220919_2233'),
    ]


