# Generated by Django 3.1.7 on 2022-09-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0007_auto_20220925_1540'),
    ]


