# Generated by Django 3.1.7 on 2022-09-25 20:47
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0013_remove_ordercontractor_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontractor',
            name='paid_fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date2'),
        ),
    ]


