# Generated by Django 3.1.7 on 2022-09-25 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0014_ordercontractor_paid_fecha'),
    ]


