# Generated by Django 3.1.7 on 2022-09-25 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0016_auto_20220925_1657'),
    ]

    operations = [

    ]
