# Generated by Django 3.1.7 on 2022-09-25 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0017_auto_20220925_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercontractor',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='ordercontractor',
            name='paid_fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ordercontractordetail',
            name='fecha',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Delivery Date'),
        ),
    ]
