# Generated by Django 3.1.7 on 2022-09-27 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0018_auto_20220925_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontractordetail',
            name='Special_Inst',
            field=models.TextField(default='', max_length=300, verbose_name='Special Instructions.'),
        ),
        migrations.AlterField(
            model_name='ordercontractor',
            name='Created_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name=' Created Date'),
        ),
        migrations.AlterField(
            model_name='ordercontractor',
            name='paid_fecha',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Paid Date'),
        ),
    ]
