# Generated by Django 3.1.7 on 2022-09-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0019_auto_20220926_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Procesed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordercontractor',
            name='closed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordercontractor',
            name='paied',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordercontractordetail',
            name='Barcode',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordercontractordetail',
            name='Other',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordercontractordetail',
            name='Sellado',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
    ]
