# Generated by Django 3.1.7 on 2022-09-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0022_ordercontractor_approve_fecha'),
    ]


