# Generated by Django 3.1.7 on 2022-09-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0023_auto_20220929_2148'),
    ]


