# Generated by Django 3.1.7 on 2022-09-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0024_remove_ordercontractor_approve_fecha'),
    ]


