# Generated by Django 3.1.7 on 2022-10-01 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0026_remove_ordercontractor_approve_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=30, verbose_name='Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),

            ],
        ),
        migrations.AddField(
            model_name='ordercontractordetail',
            name='Terminado',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='only_labeling',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Create Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.rates'),
        ),
    ]
