# Generated by Django 3.1.7 on 2022-10-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0027_auto_20221001_1116'),
    ]


