# Generated by Django 3.1.7 on 2022-10-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0028_auto_20221001_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='valor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.rates'),
        ),
    ]
