# Generated by Django 3.1.7 on 2022-10-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0029_auto_20221001_1120'),
    ]


