# Generated by Django 3.1.7 on 2022-10-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0031_delete_prices_product'),
    ]


