# Generated by Django 3.1.7 on 2022-10-02 15:11
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0032_delete_prices_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Rates', 'verbose_name_plural': 'Rates'},
        ),
        migrations.RenameField(
            model_name='ordercontractordetail',
            old_name='Other',
            new_name='Pagado',
        ),
        migrations.AddField(
            model_name='ordercontractordetail',
            name='fecha_de_pago',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Delivery Date'),
        ),
        migrations.DeleteModel(
            name='Prices_Product',
        ),
    ]
