# Generated by Django 3.1.7 on 2022-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0033_auto_20221002_1111'),
    ]


