# Generated by Django 3.1.7 on 2022-10-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0035_auto_20221002_1116'),
    ]


