# Generated by Django 3.1.7 on 2022-10-02 22:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0036_remove_ordercontractordetail_fecha_de_ago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontractordetail',
            name='fecha_de_pago',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Paid Date'),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty_Delivery', models.IntegerField(default=0, verbose_name='Qty Deliveried')),
                ('valor_unit', models.FloatField(default=0)),
                ('valor_pagado', models.FloatField(default=0)),
                ('fecha_liquidacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Delivery Date')),
                ('Orden', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.ordercontractor')),
                ('Product', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.product')),
            ],
            options={
                'verbose_name': 'OrderContractorDetail',
                'verbose_name_plural': 'OrderContractorDetail',
            },
        ),
    ]
