# Generated by Django 3.1.7 on 2022-10-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0037_auto_20221002_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Num_Liquidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Liq', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Num_Liquidacion',
                'verbose_name_plural': 'Num_Liquidacion',
            },
        ),
        migrations.AlterModelOptions(
            name='liquidacion',
            options={'verbose_name': 'Liquidacion', 'verbose_name_plural': 'Liquidacion'},
        ),
    ]
