# Generated by Django 3.1.7 on 2022-10-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0038_auto_20221002_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='Numero_Liquidacion',
            field=models.IntegerField(default=0),
        ),
    ]
