# Generated by Django 3.1.7 on 2022-10-03 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0040_auto_20221002_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='num_liquidacion',
            name='fecha_liquidacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Payment Date'),
        ),
    ]
