# Generated by Django 3.1.7 on 2022-10-06 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0041_num_liquidacion_fecha_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='num_liquidacion',
            name='Contractor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='guardog_wh.contractor'),
        ),
    ]
