# Generated by Django 3.1.7 on 2022-11-11 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0043_auto_20221028_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercontractor',
            name='paid_fecha',
        ),
        migrations.RemoveField(
            model_name='ordercontractor',
            name='paied',
        ),
        migrations.AddField(
            model_name='ordercontractordetail',
            name='fecha_quickbook',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Quickbook Date'),
        ),
        migrations.AddField(
            model_name='ordercontractordetail',
            name='user_update',
            field=models.CharField(default='', max_length=50, verbose_name='User Name'),
        ),
    ]
