# Generated by Django 3.1.7 on 2022-11-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0045_ordercontractordetail_en_quickb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsinner',
            name='Archivo_imagen',
            field=models.CharField(default='', max_length=100, verbose_name='Img File for label'),
        ),
    ]
