# Generated by Django 3.1.7 on 2022-11-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0046_orderdetailsinner_archivo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightsheet',
            name='Barcode_image',
            field=models.CharField(default='', max_length=100, verbose_name='Barcode_image'),
        ),
    ]
