# Generated by Django 3.1.7 on 2022-11-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0047_weightsheet_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightsheet',
            name='SKU_p',
            field=models.CharField(default='', max_length=100, verbose_name='Barcode_image'),
        ),
    ]
