# Generated by Django 3.1.7 on 2022-11-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0048_weightsheet_sku_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightsheet',
            name='Weight_Net',
            field=models.IntegerField(default=0, verbose_name='Net Weight'),
        ),
        migrations.AlterField(
            model_name='weightsheet',
            name='Weight',
            field=models.IntegerField(default=0, verbose_name='Gross Weight'),
        ),
    ]
