# Generated by Django 3.1.7 on 2022-11-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0049_auto_20221113_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightsheet',
            name='Total_of_Items',
            field=models.IntegerField(default=0, verbose_name='Total of Items'),
        ),
    ]
