# Generated by Django 3.1.7 on 2022-11-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0051_weightsheet_po_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightsheet',
            name='Destino_final',
            field=models.CharField(default='', max_length=100, verbose_name='Po Number'),
        ),
    ]
