# Generated by Django 3.1.7 on 2023-02-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0053_auto_20221212_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='academy',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Name2'),
        ),
    ]
