# Generated by Django 3.1.7 on 2023-02-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardog_wh', '0054_auto_20230221_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightsheet',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='Po Number'),
        ),
    ]
