# Generated by Django 3.1.7 on 2022-03-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='tipousuario',
            field=models.CharField(choices=[('G', 'Gestor'), ('C', 'Coordinador'), ('T', 'Transporte'), ('A', 'Administrativo y Control')], default='G', max_length=1),
        ),
    ]
