# Generated by Django 3.1.7 on 2022-09-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220314_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='tipousuario',
            field=models.CharField(choices=[('G', 'General - Manager'), ('C', 'Coordinador/Supervisor'), ('F', 'Financial'), ('H', 'Home Team - Contractor')], default='G', max_length=1),
        ),
    ]
