# Generated by Django 3.1.7 on 2022-10-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220920_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user2',
            options={'verbose_name': 'UsuariosFer', 'verbose_name_plural': 'UsuariosFer'},
        ),
    ]
